services:
  dev:
    profiles: ["dev"]
    build:
      context: images/dev
    image: ${COMPOSE_PROJECT_NAME:-coding-assistance-infra}/dev:latest
    command: sleep infinity
    working_dir: /opt/project
    volumes:
      - .:/opt/project
      # - /var/run/docker.sock:/var/run/docker.sock # enable if you trust you agent
    security_opt:
      - seccomp=unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local-ai

