FROM docker:28-cli

RUN apk add --no-cache \
    bash \
    curl \
    git \
    jq \
    make \
    python3 \
    py3-pip \
    py3-ruff \
    shellcheck \
    yq

WORKDIR /opt/project
CMD ["sleep", "infinity"]

